name: Publish technical documentation

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Asciidoctor and PlantUML extension
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          sudo gem install asciidoctor
          sudo gem install asciidoctor-plantuml

      - name: Build documentation
        run: |
          PLANTUML_URL="https://www.plantuml.com/plantuml" \
          PLANTUML_ENCODING="deflate" \
          asciidoctor -r asciidoctor-plantuml \
            -D build/site \
            -R src/docs/asciidoc \
            **/*.adoc

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
          publish_branch: gh-pages
          force_orphan: true
